"""
This script extracts a single variable or multiple variables from history tar files 
that is spread across multi-year and multi-ensemble files generated by a model FRE run. 
The extracted variables are stored in a specified output 
directory for further analysis.

### Module reqirements:
module load miniforge
conda activate /nbhome/role.medgrp/.conda/envs/medpy311 
module load nco/5.1.5

### Functionality:
- Efficiently extracts variables that are contained within the same model output file.
- Designed for model outputs with a consistent file-naming pattern, such as:
  `YYYYMMDD.ocean_month.nc`, where `ocean_month` is specified in the configuration file.
- Supports extracting multiple variables at once.

### Requirements:
- The script expects a configuration file (`extract_var_from_ens_forecast.json`) as input.
- The `extract_var_from_ens_forecast.json` file must specify the directories, archive naming conventions, 
  variable names, and the range of years to process.

### Example Usage:
python extract_var_from_ens_forecast.py extract_var_from_ens_forecast.json

### Example extract_var_from_ens_forecast.json Configuration:


#### Explanation of example_extract_var.json Parameters:


### Notes:
- The script is optimized for extracting variables from files that follow a structured naming convention.
- Ensure that the specified directories and files exist before running the script.
- The process may take time depending on the size of the data and number of variables.

"""

import os
import glob
import json
import sys
import logging
import subprocess
from pathlib import Path
from extract_var_from_history import setup_logging, load_config


def concat_files(
    files:list,
    output_concat_filename:str
):
    if len(files) == 0:
        logging.error(
            'single variable files do not exit'
        )
        sys.exit('Script execution error due to no yearly variable file output generated')
    else:
        logging.info(
            '(ncrcat) concatenating files for single variable, single ensemble, multi-lead ...'
        )
        command = ["ncrcat", "-O", "-h"] + files + [output_concat_filename]
        subprocess.run(command, check=True)
        logging.info(
            'concatenated file at %s ...',output_concat_filename
        )

        # remove individual files
        for file in files:
            os.remove(file)
        logging.info('remove individual files')

    return 

def extract_tar_ncks_var(
    tarball:str,
    tarball_extract_filename:str,
    temp_store_dir:str,
    output_store_dir:str,
    output_store_filename:str,
    variable_name:str
):
    # create vftmp directory if not exist
    if not os.path.exists(temp_store_dir):
        os.makedirs(temp_store_dir)

    # create output directory if not exist
    if not os.path.exists(output_store_dir):
        os.makedirs(output_store_dir)

    # getting tarball out of the tape
    subprocess.run(
        ["dmget", tarball],
        check=True
    )

    # extract file from a tarball
    vftmp_filename = os.path.join(temp_store_dir,tarball_extract_filename)
    if os.path.isfile(vftmp_filename):
        logging.warning(
            'extracted tar file %s exist, skipping...',vftmp_filename
        )
    else:
        logging.info(
            '(tar -xf) extracting tar file %s ...',vftmp_filename
        )
        # untar single file based on subexp_name
        subprocess.run(
            ["tar", "-xf", tarball, "-C", Path(temp_store_dir), './'+tarball_extract_filename],
            check=True
        )

    # extract single variable from a netCDF file using ncks
    output_var_filename = os.path.join(output_store_dir,output_store_filename)
    if os.path.isfile(output_var_filename):
        logging.warning(
            'extracted variable file %s exist, skipping...',output_var_filename
        )
    else:
        logging.info(
            '(ncks) extracting variable %s ...',output_var_filename
        )
        try:
            subprocess.run(
                ["ncks", "-O", "-h", "-v", variable_name, vftmp_filename, output_var_filename], check=True
            )
        except FileNotFoundError :
            logging.error(
                'NCO module might not be loaded. Exist execution of variable extraction.'
            )
            sys.exit('Script execution stopped due to missing NCO module')

    return

def extract_variable_ens_forecast(
    archive_dir:str,
    vftmp_dir:str,
    output_dir:str,
    subexp_name:str,
    var:str,
    initialization_year:int,
    initialization_month:int,
    ensemble_member_num:int, 
    experiment_type:str
):
    """
    1. extract only the subexp netcdf file (use tar -tf file.tar to check availability)
    2. extract single variable from the subexp nc

    Parameters
    ----------
    archive_dir : str
        the history archive path
    output_dir : str
        the output directory path
    subexp_name : str
        the output experiement name ex: ocean_month, ocean_daily ...etc
    var : str
        variable name
    initialization_year : int
        the initialization year
    initialization_month : int
        the initialization month
    ensemble_member_num : int
        the ensemble member number
    """

    # skip creating concat file if already exist
    if os.path.isfile(output_var_concat_filename):
        logging.warning(
            'concatenate file %s exist, skipping...',output_var_concat_filename
        )
    else:
        # process tracking in log file
        logging.info(
            '===== Processing initial year %4d initial month %2d ensamble_number %2d...',
            initialization_year,
            initialization_month,
            ensemble_member_num
        )
        if experiment_type == 'decadel':
            for yr in range(initialization_year, initialization_year+10):
                # specify tar file
                tar_path = Path(f"{archive_dir}/{yr:04d}0101.nc.tar")
                # specify specific nc file to extract in tar file (same file name for vftmp temp store)
                file_to_extract = f"{yr:04d}0101.{subexp_name}.nc"
                # specify output nc file
                output_filename = f'{experiment_type}.{subexp_name}.i{initialization_year}.e{ensemble_member_num}.{yr}.{var}.nc'

                extract_tar_ncks_var(
                    tarball = tar_path,
                    tarball_extract_filename = file_to_extract,
                    temp_store_dir = vftmp_dir,
                    output_store_dir = output_dir,
                    output_store_filename = output_filename,
                    variable_name = var
                )

            # find all files to concatenate lead to one
            output_var_filename_wildcard = os.path.join(output_dir,f'{experiment_type}.{subexp_name}.i{initialization_year}.e{ensemble_member_num}.????.{var}.nc')
            allfiles = glob.glob(output_var_filename_wildcard)
            output_var_concat_filename = os.path.join(
                output_dir,
                f'{experiment_type}.{subexp_name}.i{initialization_year}.e{ensemble_member_num}.{var}.nc'
            )
            concat_files(allfiles,output_var_concat_filename)
        


    return

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python extract_var_from_history.py <config_file.json>")
        sys.exit(1)

    config_file = sys.argv[1]

    # Derive the log file name from the config file
    log_file = os.path.splitext(config_file)[0] + ".log"

    # remove log file if exist
    if os.path.isfile(log_file):
        os.remove(log_file)

    try:
        # Set up logging
        setup_logging(log_file)

        # Load config
        config = load_config(config_file)
        output_directory = config["output_directory"]
        vftmp_directory = config["vftmp_directory"]
        archive_directory = config["archive_directory"]
        archive_subexp_name = config["archive_subexp_name"]
        variable_names = config["variable_names"]
        initialization_year_range = config["initialization_year_range"]
        initialization_month = int(config["initialization_month"])
        ensemble_members = config["ensemble_members"]
        forecast_type = config["forecast_type"]

        # run extract variable
        for init_year in initialization_year_range:
            for variable in variable_names:
                for ens in ensemble_members:
                    # process tracking in log file
                    logging.info(
                        '=== Processing variable %s ...',variable
                    )
                    extract_variable_ens_forecast(
                        archive_dir = archive_directory,
                        vftmp_dir = vftmp_directory,
                        output_dir = output_directory,
                        subexp_name = archive_subexp_name,
                        var = variable,
                        initialization_year= init_year,
                        initialization_month= initialization_month,
                        ensemble_member_num= ens,
                        experiment_type=forecast_type
                    )

    except (FileNotFoundError, json.JSONDecodeError) as e:
        error_message = f"ERROR: Could not read config file '{config_file}': {e}"
        logging.error(error_message)
        print(error_message)
