"""
This script extracts a single variable or multiple variables from history tar files 
that is spread across multi-year and multi-ensemble files generated by a model FRE run. 
The extracted variables are stored in a specified output 
directory for further analysis.

### Module reqirements:
module load miniforge
conda activate /nbhome/role.medgrp/.conda/envs/medpy311 
module load nco/5.1.5

### Functionality:
- Efficiently extracts variables that are contained within the same model output file.
- Designed for model outputs with a consistent file-naming pattern, such as:
  `YYYYMMDD.ocean_month.nc`, where `ocean_month` is specified in the configuration file.
- Supports extracting multiple variables at once.

### Requirements:
- The script expects a configuration file (`extract_var_from_ens_forecast.json`) as input.
- The `extract_var_from_ens_forecast.json` file must specify the directories, archive naming conventions, 
  variable names, and the range of years to process.

### Example Usage:
python extract_var_from_ens_forecast.py extract_var_from_ens_forecast.json

### Example extract_var_from_ens_forecast.json Configuration:


#### Explanation of example_extract_var.json Parameters:


### Notes:
- The script is optimized for extracting variables from files that follow a structured naming convention.
- Ensure that the specified directories and files exist before running the script.
- The process may take time depending on the size of the data and number of variables.

"""

import os
import glob
import json
import sys
import logging
import subprocess
from pathlib import Path
from extract_var_from_history import setup_logging, load_config


def concat_files(
    files:list,
    output_concat_filename:str
):
    """concat all time for decadal experiment

    Parameters
    ----------
    files : list
        list of file name to concat
    output_concat_filename : str
        output filename for the concat data
    """
    if len(files) == 0:
        logging.error(
            'single variable files do not exit'
        )
        sys.exit('Script execution error due to no yearly variable file output generated')
    else:
        logging.info(
            '(ncrcat) concatenating files for single variable, single ensemble, multi-lead ...'
        )
        command = ["ncrcat", "-O", "-h"] + files + [output_concat_filename]
        subprocess.run(command, check=True)
        logging.info(
            'concatenated file at %s ...',output_concat_filename
        )

        # remove individual files
        for file in files:
            os.remove(file)
        logging.info('remove individual files')

    return

def extract_tar_ncks_var(
    tarball:str,
    tarball_extract_filename:str,
    temp_store_dir:str,
    output_store_dir:str,
    output_store_filename:str,
    variable_name:str
):
    """extract the file from tarball and extract the variable from the file

    Parameters
    ----------
    tarball : str
        tarball file path
    tarball_extract_filename : str
        filename inside the tarball
    temp_store_dir : str
        temporary store dir
    output_store_dir : str
        output file dir
    output_store_filename : str
        output filename
    variable_name : str
        variable name to extract from the file inside the tarball
    """
    # create vftmp directory if not exist
    if not os.path.exists(temp_store_dir):
        os.makedirs(temp_store_dir)

    # create output directory if not exist
    if not os.path.exists(output_store_dir):
        os.makedirs(output_store_dir)

    # getting tarball out of the tape
    subprocess.run(
        ["dmget", tarball],
        check=True
    )

    # extract file from a tarball
    vftmp_filename = os.path.join(temp_store_dir,tarball_extract_filename)
    if os.path.isfile(vftmp_filename):
        logging.warning(
            'extracted tar file %s exist, skipping...',vftmp_filename
        )
    else:
        logging.info(
            '(tar -xf) extracting tar file %s ...',vftmp_filename
        )
        # untar single file based on subexp_name
        subprocess.run(
            ["tar", "-xf", tarball, "-C", Path(temp_store_dir), './'+tarball_extract_filename],
            check=True
        )

    # extract single variable from a netCDF file using ncks
    output_var_filename = os.path.join(output_store_dir,output_store_filename)
    if os.path.isfile(output_var_filename):
        logging.warning(
            'extracted variable file %s exist, skipping...',output_var_filename
        )
    else:
        logging.info(
            '(ncks) extracting variable %s ...',output_var_filename
        )
        try:
            subprocess.run(
                ["ncks", "-O", "-h", "-v", variable_name, vftmp_filename, output_var_filename], check=True
            )
        except FileNotFoundError :
            logging.error(
                'NCO module might not be loaded. Exist execution of variable extraction.'
            )
            sys.exit('Script execution stopped due to missing NCO module')

    return

def extract_variable_ens_forecast(
    archive_dir:str,
    vftmp_dir:str,
    output_dir:str,
    subexp_name:str,
    experiment_type:str,
    var:str,
    ensemble_member_num:int,
    initialization_year:int,
    initialization_month:int=None
):
    """
    1. extract only the subexp netcdf file (use tar -tf file.tar to check availability)
    2. extract single variable from the subexp nc

    Parameters
    ----------
    archive_dir : str
        the history archive path
    output_dir : str
        the output directory path
    subexp_name : str
        the output experiement name ex: ocean_month, ocean_daily ...etc
    var : str
        variable name
    initialization_year : int
        the initialization year
    initialization_month : int
        the initialization month
    ensemble_member_num : int
        the ensemble member number
    """
    # for decadal experiment the initialization is always Jan
    if initialization_month is None and experiment_type == 'decadal':
        initialization_month = 1
    elif initialization_month is None and experiment_type != 'decadal':
        raise IOError('initialization month not provided')

    # output concat filenames
    output_var_concat_filename = os.path.join(
        output_dir,
        f'{experiment_type}.{subexp_name}.i{initialization_year:04d}{initialization_month:02d}.e{ensemble_member_num:02d}.{var}.nc'
    )

    # skip creating concat file if already exist
    if os.path.isfile(output_var_concat_filename):
        logging.warning(
            'concatenate file %s exist, skipping...',output_var_concat_filename
        )
        return

    # process tracking in log file
    logging.info(
        '===== Processing initial year %4d initial month %2d ensamble_number %2d...',
        initialization_year,
        initialization_month,
        ensemble_member_num
    )
    if experiment_type == 'decadal':
        # for decadal file arrangement (single archive path 10 different history out start from Jan of each year)
        for yr in range(initialization_year, initialization_year+10):
            # specify tar file
            tar_path = Path(f"{archive_dir}/{yr:04d}0101.nc.tar")
            # specify specific nc file to extract in tar file (same file name for vftmp temp store)
            file_to_extract = f"{yr:04d}0101.{subexp_name}.nc"
            # specify output nc file (not concat)
            output_filename = (
                f'{experiment_type}.{subexp_name}.i{initialization_year:04d}{initialization_month:02d}.e{ensemble_member_num:02d}.{yr}.{var}.nc'
            )

            # extract single ens, single variable, single year (10years in total)
            extract_tar_ncks_var(
                tarball = tar_path,
                tarball_extract_filename = file_to_extract,
                temp_store_dir = vftmp_dir,
                output_store_dir = output_dir,
                output_store_filename = output_filename,
                variable_name = var
            )

        # find all files to concatenate time (10 years in total) for single initialization
        output_var_filename_wildcard = os.path.join(
            output_dir,
            f'{experiment_type}.{subexp_name}.i{initialization_year:04d}{initialization_month:02d}.e{ensemble_member_num:02d}.????.{var}.nc'
        )
        allfiles = glob.glob(output_var_filename_wildcard)
        concat_files(allfiles,output_var_concat_filename)
    
    elif experiment_type == 'seasonal':
        # for seasonal file arrangement (single archive path 1 history for each initial year and month)
        yr = initialization_year
        mon = initialization_month
        
        # specify tar file
        tar_path = Path(f"{archive_dir}/{yr:04d}{mon:02d}01.nc.tar")
        # specify specific nc file to extract in tar file (same file name for vftmp temp store)
        file_to_extract = f"{yr:04d}{mon:02d}01.{subexp_name}.nc"
        # specify output nc file (not concat)
        output_filename = output_var_concat_filename

        # extract single ens, single variable, single year
        extract_tar_ncks_var(
            tarball = tar_path,
            tarball_extract_filename = file_to_extract,
            temp_store_dir = vftmp_dir,
            output_store_dir = output_dir,
            output_store_filename = output_filename,
            variable_name = var
        )

    return

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python extract_var_from_ens_forecast.py <config_file.json>")
        sys.exit(1)

    config_file = sys.argv[1]

    # Derive the log file name from the config file
    log_file = os.path.splitext(config_file)[0] + ".log"

    # remove log file if exist
    if os.path.isfile(log_file):
        os.remove(log_file)

    try:
        # Set up logging
        setup_logging(log_file)

        # Load config
        config = load_config(config_file)
        output_directory = config["output_directory"]
        vftmp_directory = config["vftmp_directory"]
        archive_directory_format = config["archive_directory_format"]
        archive_subexp_name = config["archive_subexp_name"]
        variable_names = config["variable_names"]
        initialization_year_range = config["initialization_year_range"]
        initialization_mon = int(config["initialization_month"])
        ensemble_members = config["ensemble_members"]
        forecast_type = config["forecast_type"]
        release_tag = config["release_tag"]

        # run extract variable
        for variable in variable_names:
            for init_year in initialization_year_range:
                for ens in ensemble_members:
                    vftmp_directory_sub = vftmp_directory+f"_{forecast_type}_{init_year}_{initialization_mon}_{ens}_{release_tag}"
                    # process archive path based on format
                    archive_directory = archive_directory_format.replace("YYYY",f"{init_year:04d}")
                    archive_directory = archive_directory.replace("MM",f"{initialization_mon:02d}")
                    if "eEE" in archive_directory:
                        archive_directory = archive_directory.replace("eEE",f"e{ens:02d}")
                    elif "eE" in archive_directory:
                        archive_directory = archive_directory.replace("eE",f"e{ens}")

                    # check if the archive exist if not skip to next ens
                    if not os.path.exists(archive_directory):
                        logging.warning(
                            '=== Archive %s does not exist skipping...',archive_directory
                        )
                        continue

                    # process tracking in log file
                    logging.info(
                        '=== Processing variable %s ...',variable
                    )
                    extract_variable_ens_forecast(
                        archive_dir = archive_directory,
                        vftmp_dir = vftmp_directory_sub,
                        output_dir = output_directory,
                        subexp_name = archive_subexp_name,
                        var = variable,
                        initialization_year= init_year,
                        initialization_month= initialization_mon,
                        ensemble_member_num= ens,
                        experiment_type=forecast_type
                    )

    except (FileNotFoundError, json.JSONDecodeError) as e:
        error_message = f"ERROR: Could not read config file '{config_file}': {e}"
        logging.error(error_message)
        print(error_message)
